/**
 * Simulates a grocery receipt generated by a clerk
 * @author Ammar Husain
 * Period 4
 */
public class GroceryReceipt {
    private Employee clerk;//Employee object representing the clerk generating the receipt
    private String receipt;//List of items
    private double total;//Total price
    /***
     * Initializes the clerk to the passed in employee,
     * the receipt to an empty string and total to 0
     * @param c - employee generating this receipt
     */
    public GroceryReceipt(Employee c){
        clerk = c;
        receipt = "";
        total = 0;
    }
    /**
     * Returns the clerk generating the information
     * @return clerk
     */
    public Employee getClerk(){
        return this.clerk;
    }
    /**
     * Returns the list of items
     * @return receipt
     */
    public String getReceipt(){
        return this.receipt;
    }
    /**
     * Returns the total amount on this receipt in dollars and cents
     * @return total amount
     */
    public double getTotal(){
        return this.total;
    }
    /**
     * Adds the given item to the receipt
     * Updates the total by adding in the the items price
     * @param i - grocery item to be added
     */
    public void add(Item i){
        receipt += i.toString() + "\n";
        total += i.getPrice();
    }
    /**
     * Returns the value passed as a string in the dollar and cents format ####.##
     * @param d - value to be converted to dollar and cents format
     * @return String in dollar and cents format
     */
    public String valueToString(double d){
        String s = "" + Math.round(d*100)/100.0;
        if(s.length() - s.indexOf(".") <3){
            s += "0";
        }
        return s;
    }
    /**
     * Returns a string with list of items (one per line) and total receipt amount
     * @return a string with list of items and total receipt amount
     */
    public String toString(){
        return getReceipt() + "\n" + "Total: $" + valueToString(getTotal());
    }
}
